// <auto-generated>
//     Archivo generado automáticamente.
// </auto-generated>

namespace ReservaVuelos
{
    public partial class AdminVuelos
    {
        protected global::System.Web.UI.WebControls.Label lblMsg;
        protected global::System.Web.UI.WebControls.TextBox txtOrigen;
        protected global::System.Web.UI.WebControls.TextBox txtDestino;
        protected global::System.Web.UI.WebControls.TextBox txtFecha;
        protected global::System.Web.UI.WebControls.TextBox txtHora;
        protected global::System.Web.UI.WebControls.TextBox txtPrecio;
        protected global::System.Web.UI.WebControls.TextBox txtCupos;
        protected global::System.Web.UI.WebControls.Button btnCrear;
        protected global::System.Web.UI.WebControls.DropDownList ddlFiltro;
        protected global::System.Web.UI.WebControls.GridView gvVuelosAdmin;
    }
}
