// <auto-generated>
//     Archivo generado automáticamente.
// </auto-generated>

namespace ReservaVuelos
{
    public partial class Backup
    {
        protected global::System.Web.UI.WebControls.Label lblBackupAviso;
        protected global::System.Web.UI.WebControls.Button btnGenerarBackup;
        protected global::System.Web.UI.WebControls.Label lblBackupNombre;
        protected global::System.Web.UI.WebControls.Label lblBackupFechaHora;
        protected global::System.Web.UI.WebControls.Label lblBackupRuta;
        protected global::System.Web.UI.WebControls.Label lblBackupResultado;
        protected global::System.Web.UI.WebControls.Label lblBackupMensaje;
        protected global::System.Web.UI.WebControls.Button btnActualizarListaBackups;
        protected global::System.Web.UI.WebControls.GridView gvBackupsDisponibles;
        protected global::System.Web.UI.WebControls.Label lblBackupSeleccionado;
        protected global::System.Web.UI.WebControls.HiddenField hfBackupSeleccionado;
        protected global::System.Web.UI.WebControls.Button btnRestaurarBackup;
        protected global::System.Web.UI.WebControls.Label lblRestoreResultado;
        protected global::System.Web.UI.WebControls.Label lblRestoreMensaje;
    }
}
