// <auto-generated>
//     Archivo generado automáticamente.
// </auto-generated>

namespace ReservaVuelos
{
    public partial class Bitacora
    {
        protected global::System.Web.UI.WebControls.Label lblMsg;
        protected global::System.Web.UI.WebControls.GridView gvBitacora;
    }
}
