// <auto-generated>
//     Archivo generado automáticamente.
// </auto-generated>

namespace ReservaVuelos
{
    public partial class BuscarVuelos
    {
        protected global::System.Web.UI.WebControls.Label lblMsg;
        protected global::System.Web.UI.WebControls.TextBox txtOrigen;
        protected global::System.Web.UI.WebControls.TextBox txtDestino;
        protected global::System.Web.UI.WebControls.DropDownList ddlTipoViaje;
        protected global::System.Web.UI.WebControls.TextBox txtFecha;
        protected global::System.Web.UI.WebControls.TextBox txtFechaVuelta;
        protected global::System.Web.UI.WebControls.Button btnBuscar;
        protected global::System.Web.UI.WebControls.GridView gvVuelos;
    }
}
